jms5049/CRA_SSD

SSD/SSD/SSD.vcxproj
SSD/SSD/SSD.vcxproj.filters
SSD/SSD/read.cpp
SSD/SSD_Test/test.cpp

read 함수 추가 
우선 입력이 들어왔을 때 "R XX" 형식으로 제대로 들어왔는지 검증하는 Exception 처리하는 코드를 구현하였고, 여기서 index를 추출하는 부분까지 구현하였습니다.
To do: nand.txt에서 값을 읽어와서 return 한 다음 result.txt에 저장하기 
어떤 변경 사항이 있나요?

[Add] Add read function

---

TestShell/TestShell/TestShell.cpp
TestShell/TestShell/TestShell.h

conflict 해결이 제대로 되지 않아 빌드 에러가 있었습니다. 수정하였습니다. 
어떤 변경 사항이 있나요?

[Refactoring] conflict 오류 해결

---

TestShell/TestShell/TestShell.cpp
TestShell/TestShell/TestShell.h
TestShell/TestShell_Test/TestShell_test.cpp

TestShell에 fullwrite 기능 추가하고 TC를 Fixture 사용하도록 refactoring 했습니다.
어떤 변경 사항이 있나요?

[add] TestShell fullwrite 기능 추가 (SsdApi는 Mock 사용)

---

TestShell/TestShell/TestShell.cpp
TestShell/TestShell_Test/TestShell_test.cpp

입력값 정규표현식으로 검증하도록 수정했습니다.
코드 라인수가 줄었어요 :)
어떤 변경 사항이 있나요?

[refactoring] TestShell Write 입력값을 정규 표현식으로 검증하도록 수정

---

TestShell/TestShell/TestShell.cpp
TestShell/TestShell_Test/TestShell_test.cpp

[feature] Improve test coverage for TestShell

---

TestShell/TestShell/Ssd.cpp
TestShell/TestShell/Ssd.h
TestShell/TestShell_Test/TestShell_test.cpp

TestShell 에서 실제 SSD.exe 를 호출하여 write 할 수 있도록 Ssd class의 write 기능을 구현했습니다.
read 기능이 작성되기 전이라 TC에서는 method 호출만 하고 txt 변경을 눈으로 확인했습니다.
추후 read 기능이 완성되면 write -> read 해서 검증할 수 있을 것 같습니다.
어떤 변경 사항이 있나요?

[feature] TestShell Ssd class의 write 기능 구현

---

TestShell/TestShell/Ssd.cpp
TestShell/TestShell/Ssd.h

LPCSTR을 사용하는 대신 string 쓰도록 수정했습니다.
어떤 변경 사항이 있나요?

[fix] LPCSTR 인식 못하는 이슈 수정

---

TestShell/TestShell/TestShell.cpp
TestShell/TestShell/TestShell.h

read()함수에서 result.txt에서 읽은 값을 리턴 하는 부분을 추가하였습니다. 
어떤 변경 사항이 있나요?

[Refactoring] read() return type 변경

---

TestShell/TestShell_Test/TestShell_test.cpp

SSD.exe 로 full write Test 시 nand.txt 변경되는 것원복하도록 했습니다.
어떤 변경 사항이 있나요?

[refactoring] SSD.exe 로 Test 후 nand.txt 원복

---

TestShell/TestShell/main.cpp

Testshell main function에서 user input을 받아 testshell or testscript function을 불러주는 부분 구현하였습니다.
어떤 변경 사항이 있나요?

[feature] add main function for test shell

---

TestShell/TestShell/TestScript.h

git update 오류로 인한 error 제거 
어떤 변경 사항이 있나요?

<mod> git update 오류로 인한 error 제거

---

SSD/SSD_Test/Ssd_test.cpp

SSD test coverage 100%를 위해 TC 추가하였습니다.
어떤 변경 사항이 있나요?

[feature] Improve testcoverage for SSD

---

TestShell/TestShell/main.cpp

[feature] TestShell main 에서 exception 타입에 따라 error 출력하도록 했습니다.
어떤 변경 사항이 있나요?

[feature] TestShell main 의 exception 타입에 따른 error 출력

---

TestShell/TestShell/TestShell.cpp
TestShell/TestShell_Test/TestShell_test.cpp

fullwrite 시 argument 개수 잘못 받는 이슈 수정
어떤 변경 사항이 있나요?

[fix] fullwrite 시 argument 개수 잘못 받는 이슈 수정

---

TestShell/TestShell/Ssd.cpp
TestShell/TestShell/TestShell.cpp

read() 에서 15ms delay를 추가하였습니다. 
어떤 변경 사항이 있나요?

[Add] delay 기능 추가

---

TestShell/TestShell/Ssd.cpp
TestShell/TestShell/TestShell.cpp

readResultFile()과 fullRead()에서 endline읽는 방식을 변경하였습니다. 
TestApp1, TestApp2 모두 통과합니다. 
어떤 변경 사항이 있나요?

[Refactoring] endline 처리 변경

---

TestShell/TestShell/Ssd.cpp
TestShell/TestShell/Ssd.h

Shell에서 ssd.exe 호출할 때 delay 대신 Process 종료 대기 코드 추가
어떤 변경 사항이 있나요?

[feature] Shell에서 ssd.exe 호출할 때 Process 종료 대기 코드 추가

---

TestShell/TestShell/Ssd.h

[fix] 누락된 파일 수정점 반영
어떤 변경 사항이 있나요?

[fix] Shell executeSsdCmd 누락된 파일 수정점 반영

---

TestShell/TestShell/Runner.cpp
TestShell/TestShell/Runner.h
TestShell/TestShell/TestScript.cpp
TestShell/TestShell/TestScript.h
TestShell/TestShell/TestShell.vcxproj
TestShell/TestShell/TestShell.vcxproj.filters
TestShell/TestShell/main.cpp
TestShell/TestShell/script.txt

Runner app 추가
script.txt sample 추가
사용법 :
runner script.txt
파일명 변경 가능하며, 파일 내부에서 사용 가능한 시나리오는
testapp1
testapp2
Write10AndCompare
Read10AndCompare
4가지입니다.
시나리오 상세 설명
Write10AndCompare: LBA0에 write 10번 후 read하여 값 비교
Read10AndCompare: LBA0을 10번 read하면서 값 비교
어떤 변경 사항이 있나요?

[feature] Add Runner app

---

TestShell/TestShell/TestShell.cpp

새로 추가한 erase, erase_range 및 관련 함수에서 발생하는 exception 빌드 이슈를 해결하였습니다. 
어떤 변경 사항이 있나요?

[Refactoring] Exception 빌드 이슈 해결

---

TestShell/TestShell/TestShell.cpp
TestShell/TestShell/TestShell.h
TestShell/TestShell/main.cpp

help_erase, help_erase_range 추가 및 cmd 명령어 추가 
어떤 변경 사항이 있나요?

[Add] help_erase, help_erase_range 추가 및 main 함수 추가된 명령어 추가

---

TestShell/TestShell/Command/CommandFactory.cpp
TestShell/TestShell/Command/CommandFactory.h
TestShell/TestShell/Command/EraseCommand.cpp
TestShell/TestShell/Command/EraseCommand.h
TestShell/TestShell/Command/EraseRangeCommand.cpp
TestShell/TestShell/Command/EraseRangeCommand.h
TestShell/TestShell/Command/ExitCommand.cpp
TestShell/TestShell/Command/ExitCommand.h
TestShell/TestShell/Command/FullReadCommand.cpp
TestShell/TestShell/Command/FullReadCommand.h
TestShell/TestShell/Command/FullWriteCommand.cpp
TestShell/TestShell/Command/FullWriteCommand.h
TestShell/TestShell/Command/HelpCommand.cpp
TestShell/TestShell/Command/HelpCommand.h
TestShell/TestShell/Command/ICommand.h
TestShell/TestShell/Command/IoCommand.cpp
TestShell/TestShell/Command/IoCommand.h
TestShell/TestShell/Command/ReadCommand.cpp
TestShell/TestShell/Command/ReadCommand.h
TestShell/TestShell/Command/WriteCommand.cpp
TestShell/TestShell/Command/WriteCommand.h
TestShell/TestShell/Runner.cpp
TestShell/TestShell/TestScript.cpp
TestShell/TestShell/TestScript.h
TestShell/TestShell/TestShell.cpp
TestShell/TestShell/TestShell.h
TestShell/TestShell/TestShell.vcxproj
TestShell/TestShell/TestShell.vcxproj.filters
TestShell/TestShell/main.cpp

[refactoring] 각 command를 class화하여 factory에서 생성함.
conflict 해결 후 기본적으로 command 동작 확인했습니다.
어떤 변경 사항이 있나요?

[refactoring] 각 command를 class화하여 factory에서 생성함.

---

TestShell/TestShell/Command/CommandFactory.h
TestShell/TestShell/TestShell.cpp
TestShell/TestShell/TestShell.h
TestShell/TestShell/TestShell.vcxproj
TestShell/TestShell/TestShell.vcxproj.filters
TestShell/TestShell/main.cpp

TestShell이 지원하는 command가 있는지 여부를 확인하는 method가 main.cpp와 CommandFactory 두 곳에 있어 통합.
어떤 변경 사항이 있나요?

[refactoring] 동일한 역할을 하는 method 통합

---

TestShell/TestShell/Runner.cpp
TestShell/TestShell/main.cpp

Runner에서 요구사항대로 입력값을 받아 동작하도록 수정
명령 프롬프트에서 "TestShell test.txt" 와 같이 호출 시 runner가 동작하도록 수정했습니다.
어떤 변경 사항이 있나요?

[refactoring] Runner에서 요구사항대로 입력값을 받아 동작하도록 수정

---

TestShell/TestShell/Command/CommandFactory.cpp
TestShell/TestShell/Command/FlushCommand.cpp
TestShell/TestShell/Command/FlushCommand.h
TestShell/TestShell/Ssd.cpp
TestShell/TestShell/Ssd.h
TestShell/TestShell/SsdApi.h
TestShell/TestShell/TestShell.vcxproj
TestShell/TestShell/TestShell.vcxproj.filters

Shell에 Flush Command 추가했습니다.
어떤 변경 사항이 있나요?

[feature] Shell에 Flush Command 기능 추가

---

TestShell/TestShell/Command/IoCommand.cpp

[fix] Shell LBA 범위 체크 parameter 수정 누락 fix
어떤 변경 사항이 있나요?

[fix] Shell LBA 범위 체크 parameter 수정 누락 fix

---

TestShell/TestShell/Command/HelpCommand.cpp

help command의 parameter 없이 입력 시 abort 나는 이슈 해결
어떤 변경 사항이 있나요?

[fix] fix abort when help command does not have parameter

---

TestShell/TestShell/Command/HelpCommand.cpp
TestShell/TestShell/Command/HelpCommand.h

Flush help command 추가
어떤 변경 사항이 있나요?

[feature] add flush help

---

TestShell/TestShell/Runner.cpp
TestShell/TestShell/TestScenario/Read10AndCompare.cpp
TestShell/TestShell/TestScenario/Read10AndCompare.h
TestShell/TestShell/TestScenario/TestApp1.cpp
TestShell/TestShell/TestScenario/TestApp1.h
TestShell/TestShell/TestScenario/TestApp2.cpp
TestShell/TestShell/TestScenario/TestApp2.h
TestShell/TestShell/TestScenario/TestScenario.cpp
TestShell/TestShell/TestScenario/TestScenario.h
TestShell/TestShell/TestScenario/Write10AndCompare.cpp
TestShell/TestShell/TestScenario/Write10AndCompare.h
TestShell/TestShell/TestScript.cpp
TestShell/TestShell/TestScript.h
TestShell/TestShell/TestShell.h
TestShell/TestShell/TestShell.vcxproj
TestShell/TestShell/TestShell.vcxproj.filters
TestShell/TestShell/main.cpp

TestScript.cpp 에 TC 추가 시 매번 rebuild 하지 않아도 되도록 각각을 TestScenario class를 상속받도록 수정했습니다.
TC 추가 시 TestScenario class를 상속받아 구현 후 TestScript.cpp 에 include 추가하시고  됩니다.
TC 추가하기 편하도록 추가 refactoring 하겠습니다.
ex1) 신규 Test Scenario 추가 시 아래처럼 추가된 TS.cpp 파일과 TestScript.cpp만 build 합니다.
ex2) Read10AndCompare 만 수정 시 아래처럼 build 하면 해당 file 만 build를 다시 합니다.
어떤 변경 사항이 있나요?

[add&refactoring] TestScript 추가 시 Rebuild 이슈 수정

---

TestShell/TestShell/TestShell.cpp

Command를 생성(new)만 하고 삭제(delete)를 안 해주고 있어서 메모리 누수가 발생하는 거 같아 수정
어떤 변경 사항이 있나요?

[fix] 다음 Command 수행 전 기존 Command delete 추가

---

TestShell/TestShell/TestScenario/TestApp2.cpp
TestShell/TestShell/TestScript.cpp
TestShell/TestShell/TestScript.h
TestShell/TestShell/main.cpp

[refactoring] TestScript 에서 TestScenario 생성 코드 refactoring
[fix] TestApp2 시나리오와 코드가 다르게 작성된 부분 수정
어떤 변경 사항이 있나요?

[refactoring&fix] TestScript 에서 TestScenario 생성 코드 refactoring
